---
title: "Kenya SHS round 2 data check"
author: '[Matt Lowes](mailto:email@oneacrefund.org)'
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  html_notebook:
    number_sections: yes
    code_folding: hide
    theme: flatly
    toc: yes
    toc_depth: 6
    toc_float: yes
---

```{r setup, include=FALSE}
#### set up
## clear environment and console
rm(list = ls())
cat("\014")

## set up some global options
# always set stringsAsFactors = F when loading data
options(stringsAsFactors=FALSE)

# show the code
knitr::opts_chunk$set(echo = TRUE)

# define all knitr tables to be html format
options(knitr.table.format = 'html')

# change code chunk default to not show warnings or messages
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

## load libraries
# dplyr and tibble are for working with tables
# reshape is for easy table transformation
# knitr is to make pretty tables at the end
# ggplot2 is for making graphs
# readxl is for reading in Excel files
# MASS is for running boxcox tests
# gridExtra is for arranging plots
# cowplot is for adding subtitles to plots
# robustbase is to run robust regressions to compensate for outliers
# car is for performing logit transformations
libs <- c("tidyverse", "knitr",  "readxl", "datatable")
lapply(libs, require, character.only = T, quietly = T, warn.conflicts = F)

#### define helpful functions
# define function to adjust table widths
html_table_width <- function(kable_output, width) {
  width_html <- paste0(paste0('<col width="', width, '">'), collapse = "\n")
  sub("<table>", paste0("<table>\n", width_html), kable_output)
}
```

# Objectives

Check data that has come in. Here import the data and save it so I can try working on it with Jupyter.

```{r}
source("../oaflib/commcareExport.R")

#app <- getAppStructure("harvest")

# json <- formToExportJson(getFormFromApp(getAppStructure(
#     "harvest"), "M&E Core Surveys 2018", "Soil Health Study"))


d <- getFormData("harvest", "M&E Core Surveys 2018", "Soil Health Study", forceUpdate = T)


# # break down d to figure out why the commcare export isn't working.
# # get appStructure works but then the next step fails
app <- getAppStructure("harvest", forceUpdate = T)
# 
# # I think it's because the first element of the export is not data.
form <- getFormFromApp(app, "M&E Core Surveys 2018", "Soil Health Study")
# 
# # then form to exportJson
exportjson <- formToExportJson(form)
# 
# # then json to csv
csv <- jsonToCsv(exportjson, "harvest", forceUpdate = T)

```

```{r}
d <- as.data.frame(sapply(d, as.character))
d[d=="---"] <- NA
```

There aren't many numeric variables. Find a way to convert variables to numeric without forced coersion. 

```{r}
#numVars <- names(d)[sapply(d, is.numeric)]

as.numeric.coersion <- function(x){
  result = tryCatch({
    as.numeric(x)
}, warning = function(w) {
    return(as.character(x))
  }, error = function(e) {
    return(as.character(x))
})
  #return(result)
}

# works fine on one variable
class(as.numeric.coersion(d$`How many chickens do you own?`))
table(as.numeric.coersion(d$`How many chickens do you own?`))

#class(as.numeric.coersion(d$`Site Name:`))
#table(as.numeric.coersion(d$`Site Name:`))

# doesn't work on the df
numVars <- as.data.frame(sapply(d, function(input){as.numeric.coersion(input)})) 
class(numVars$`How many chickens do you own?`)
str(numVars)
```


# Output

# Appendix
